name: Update Combat Data

on:
  # Run daily at 6pm UTC (8pm Kyiv time in winter, 9pm in summer)
  schedule:
    - cron: '0 18 * * *'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Run scraper
        run: python scraper.py
      
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Check if there are changes
          if git diff --quiet combat-data.json; then
            echo "No changes to commit"
          else
            git add combat-data.json
            git commit -m "Update combat data - $(date -u +%Y-%m-%d)"
            git push
          fi
